on: 
  push:
    branches: [ production ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy on Production
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.prod_ftp_host }}
        username: ${{ secrets.prod_ftp_username }}
        password: ${{ secrets.prod_ftp_password }}
